### Playing arund with Iris ###

We will use Iris in class to practice some attribute transformations and computing similarities.


In [1]:
import matplotlib.pyplot as plt
from sklearn import datasets

#import some data to play with
iris = datasets.load_iris()
X = iris.data[:, 2:4]  # we only take petal length and petal width. ##we take all rows, 2nd and 3rd col
Y = iris.target   #inherent property of the dataset: iris

plt.figure(2, figsize=(12, 6))  #increased horizontal length
plt.clf()

# Plot the training points
# Attribute(col) Information:
#    1. sepal length in cm
#    2. sepal width in cm
#    3. petal length in cm
#    4. petal width in cm
#    5. class: 
#       -- Iris Setosa
#       -- Iris Versicolour
#       -- Iris Virginica
plt.scatter(X[:, 0], X[:, 1], c=Y)
plt.xlabel('Petal length')
plt.ylabel('Petal width')

plt.show()

<Figure size 1200x600 with 1 Axes>

In [2]:
import numpy as np
A = iris.data
a = A[0,:]
b = A[-1,:]
print(a,b)

[5.1 3.5 1.4 0.2] [5.9 3.  5.1 1.8]


In [3]:
c = np.log(a)    #taking log of 1st row and all columns
print (c)

[ 1.62924054  1.25276297  0.33647224 -1.60943791]


In [5]:
d = np.abs(c)    #taking absolute value to remove negative values
print(d)

[1.62924054 1.25276297 0.33647224 1.60943791]


In [6]:
for i in range(A.shape[1]):
    print(np.min(A[:,i]), np.max(A[:,i]))

4.3 7.9
2.0 4.4
1.0 6.9
0.1 2.5


In [7]:
c = A[:,0]   #take all rows and 1st column of iris.data (dataset)
c_mean = np.mean(c)
c_std = np.std(c)
d = (c-c_mean)/c_std    #acc. to slides, standardization of data: subtract mean and dived by standard deviation
print(c_mean, c_std)
print(np.min(d), np.max(d), np.mean(d), np.std(d))

5.843333333333334 0.8253012917851409
-1.870024133847019 2.4920192021244283 -4.736951571734001e-16 1.0


In [8]:
#expected from us: run the code and if possible play with it to get other possible results
print (d)   #All values of standardized data - 'd'

[-0.90068117 -1.14301691 -1.38535265 -1.50652052 -1.02184904 -0.53717756
 -1.50652052 -1.02184904 -1.74885626 -1.14301691 -0.53717756 -1.26418478
 -1.26418478 -1.87002413 -0.05250608 -0.17367395 -0.53717756 -0.90068117
 -0.17367395 -0.90068117 -0.53717756 -0.90068117 -1.50652052 -0.90068117
 -1.26418478 -1.02184904 -1.02184904 -0.7795133  -0.7795133  -1.38535265
 -1.26418478 -0.53717756 -0.7795133  -0.41600969 -1.14301691 -1.02184904
 -0.41600969 -1.14301691 -1.74885626 -0.90068117 -1.02184904 -1.62768839
 -1.74885626 -1.02184904 -0.90068117 -1.26418478 -0.90068117 -1.50652052
 -0.65834543 -1.02184904  1.40150837  0.67450115  1.2803405  -0.41600969
  0.79566902 -0.17367395  0.55333328 -1.14301691  0.91683689 -0.7795133
 -1.02184904  0.06866179  0.18982966  0.31099753 -0.29484182  1.03800476
 -0.29484182 -0.05250608  0.4321654  -0.29484182  0.06866179  0.31099753
  0.55333328  0.31099753  0.67450115  0.91683689  1.15917263  1.03800476
  0.18982966 -0.17367395 -0.41600969 -0.41600969 -0.

In [9]:
list(iris.target_names)    #inherent property of dataset: iris

['setosa', 'versicolor', 'virginica']

In [10]:
np.__version__

'1.14.3'